#! /bin/sh -e

set_dpms() {
    standby_time=$(gsettings get org.pantheon.dpms standby-time | cut -d" " -f2)

    suspend_time=$(gsettings get org.pantheon.dpms suspend-time | cut -d" " -f2)

    off_time=$(gsettings get org.pantheon.dpms off-time | cut -d" " -f2)

    echo "org.gnome.settings-daemon.plugins.power manage-dpms-defaults is false.
Using settings found in org.pantheon.dpms (0 seconds = Never).
    Standby: $standby_time seconds
    Suspend: $suspend_time seconds
    Off: $off_time seconds"

    exec xset dpms "$standby_time" "$suspend_time" "$off_time"
}

gsd_status=$(gsettings get org.gnome.settings-daemon.plugins.power manage-dpms-defaults)

if [ "$gsd_status" = "false" ] ; then
    set_dpms
else
    echo "manage-dpms-defaults is true or nonexistent.
    GNOME Settings Daemon is handling DPMS instead. Nothing to do."
fi
