.TH elementary-dpms-helper 1 "January 15, 2016"
.SH NAME
elementary-dpms-helper \- sets DPMS settings found in org.pantheon.dpms
.SH DESCRIPTION
Sets DPMS settings found in org.pantheon.dpms.
.PP
This program is designed to be called by elementary OS directly when GNOME Settings Daemon is
not managing the related settings. It is probably not useful for users.
.SH COPYRIGHT
This manual page is Copyright 2016 Cody Garver <cody@elementary.io>.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Lesser General Public License, Version 2.1 or any
later version published by the Free Software Foundation.
