#!/bin/sh

if [ "$1" = "configure" ] && [ -d /usr/share/plank/themes/Pantheon ]; then
ln --symbolic --no-target-directory /usr/share/plank/themes/Pantheon /etc/skel/.config/plank/theme
fi

#DEBHELPER#
