#!/bin/sh
set -e

case "$1" in
  configure|upgrade)
    update-alternatives --set x-cursor-theme /usr/share/icons/elementary/cursor.theme
    /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
  ;;
esac

# Remove old apparmor profile
rm /etc/apparmor.d/bwrap-userns-restrict || true

#DEBHELPER#
