#!/bin/sh
set -e

case "$1" in
  configure|upgrade)
    update-alternatives --set x-cursor-theme /usr/share/icons/elementary/cursor.theme
    /usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/
  ;;
esac

# Fix flatpak updates:
ln -s /usr/share/apparmor/extra-profiles/bwrap-userns-restrict /etc/apparmor.d/ || true

#DEBHELPER#

# Plymouth HiDPI support

if [ -x /bin/systemctl ] || [ -x /usr/bin/systemctl ]; then
    systemctl preset plymouth-hidpi.service || true
    systemctl enable plymouth-hidpi.service || true
fi
