#!/bin/sh

# Restore imagemagick's undesirable display-im6.desktop and display-im6.q16.desktop
if [ "$1" = remove ] ; then
	dpkg-divert --remove --rename --package elementary-default-settings --divert /usr/share/applications/display-im6.desktop.distrib /usr/share/applications/display-im6.desktop
	dpkg-divert --remove --rename --package elementary-default-settings --divert /usr/share/applications/display-im6.q16.desktop.distrib /usr/share/applications/display-im6.q16.desktop
fi
